# SPDX-License-Identifier: MPL-2.0
# This is the 1Password SSH agent config file, which allows you to customize the
# behavior of the SSH agent running on this machine.
#
# You can use it to:
# * Enable keys from other vaults than the Private vault
# * Control the order in which keys are offered to SSH servers
#
# EXAMPLE
#
# By default, all keys in your Private vault(s) are enabled:
#
#  [[ssh-keys]]
#  vault = "Private"
#
# You can enable more keys by adding more `[[ssh-keys]]` entries.
# For example, to first enable item "My SSH Key" from "My Custom Vault":
#
#  [[ssh-keys]]
#  item = "My SSH Key"
#  vault = "My Custom Vault"
#
#  [[ssh-keys]]
#  vault = "Private"
#
# You can test the result by running:
#
#  SSH_AUTH_SOCK=~/.1password/agent.sock ssh-add -l
#
# More examples can be found here:
#  https://developer.1password.com/docs/ssh/agent/config
"$schema" = "https://developer.1password.com/schema/ssh-agent-config.json"

## Personal ##
# releases
[[ssh-keys]]
vault = "sah2xx3ps2rfhyi2svj5yzv2qu"
item = "snnlyiqrvnfqycon7ackffb3ty"
account = "https://andreijiroh-dev.1password.com"

# main key since 2022
[[ssh-keys]]
vault = "apwipwtqx6l4eqa27su7hlczey"
item = "47mdejtly5eebvh74h3vvxr2ki"
account = "https://andreijiroh-dev.1password.com"

# launchpad.net
[[ssh-keys]]
vault = "apwipwtqx6l4eqa27su7hlczey"
item = "npdvnvxih5gsr3cxlonbkayoy4"
account = "https://andreijiroh-dev.1password.com"

# infraops
[[ssh-keys]]
vault = "fykuds2mmz7iletnsxkl47slbi"
item = "ylcrbks3tkxtsgkc5gadm2dyqa"
account = "https://andreijiroh-dev.1password.com"

[[ssh-keys]]
item = "gj75ey6dr7scrckvjp33dqz3xi"
account = "https://andreijiroh-dev.1password.com"

## RecapTime.dev ##
# crew.recaptime.dev
[[ssh-keys]]
vault = "Employee"
item = "wklfmur3fegpajjhrx4acwcscm"
account = "https://recaptime-dev.1password.com"
