#!/usr/bin/env bash

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

alias ..='cd ..'
alias ...='cd ../..'

# git
alias clone='git clone'
alias status='git status'
alias stats='git status'
alias stash='git stash'
alias commit='git commit'
alias signoff='git commit --signoff'
alias push='git push'
alias fetch='git fetch'
alias pull='git pull --rebase'
alias remotes='git remote -v'
alias switch-upstream='git branch -u'
alias module="git submodule"
alias update-module="git submodule update --remote --merge"
